modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="strangerthin"
version="1.0.0"
displayName="Stranger Thin"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="louet, MCreator"

[[dependencies.strangerthin]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




